USE SimpleBistro;

-- Random payment type generated by use or RAND function and FLOOR function - should be range 1-5
INSERT INTO Payment (OrderID, PaymentTypeID, Amount)
SELECT OrderID, FLOOR((RAND()*(6-1)+1)), Total
FROM `Order`;